-- =====================================================================================
-- Atividades, gabarito, respostas e entregas dos alunos (Supabase / PostgreSQL)
-- Plano: docs/respostas-atividades-banco-painel-professor.md  —  2026-09-28
--
-- Idempotente: pode ser executado mais de uma vez (if not exists / drop policy if exists).
-- Executar no Supabase → SQL Editor. Depois rodar 2026-09-28-seed-atividades.sql.
--
-- Hierarquia: curso ← materia.curso_id ← aulas.materia_id ← atividade.aula_id
-- Perfil confiável: auth.jwt() → app_metadata.perfil (só a chave service_role altera).
-- =====================================================================================

-- ── 1. Matéria passa a ter o curso (a N-N cursomateria continua para compatibilidade) ──
alter table public.materia add column if not exists curso_id bigint references public.curso(id);
create index if not exists materia_curso_id_idx on public.materia (curso_id);

-- Preenche o curso das matérias existentes que têm exatamente um curso em cursomateria
update public.materia m
   set curso_id = cm.cursoid
  from (select materiaid, min(cursoid) as cursoid
          from public.cursomateria group by materiaid having count(*) = 1) cm
 where cm.materiaid = m.id and m.curso_id is null;

-- ── 2. Tabelas novas ──────────────────────────────────────────────────────────────────
create table if not exists public.turma (
  codigo      text primary key,                         -- ex.: 135080
  nome        text not null,                            -- ex.: AI AOPL 2026/2 M1
  turno       text,
  horario     text,
  created_at  timestamptz not null default now()
);

create table if not exists public.aluno (
  id              uuid primary key references auth.users (id) on delete cascade,
  nome            text not null,
  email           text not null unique,
  turma_codigo    text references public.turma (codigo),
  numero_chamada  integer,
  na_chamada      boolean not null default true,
  created_at      timestamptz not null default now()
);

-- atividade: JÁ EXISTE no banco (id, nome_atividade, status, quiz, created_at, updated_at — quiz
-- antigo "QUALIDADE"). Não é recriada: só ganha as colunas novas; nada existente é apagado.
-- As colunas novas são nuláveis porque a linha antiga não tem aula/página.
create table if not exists public.atividade (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now()
);
alter table public.atividade add column if not exists aula_id bigint references public.aulas (id);
alter table public.atividade add column if not exists data_atividade date;
alter table public.atividade add column if not exists descricao text;
alter table public.atividade add column if not exists pagina text;        -- location.pathname do HTML
alter table public.atividade add column if not exists total_itens integer check (total_itens > 0);
alter table public.atividade add column if not exists ativo boolean not null default true;
create unique index if not exists atividade_pagina_key on public.atividade (pagina);
create index if not exists atividade_aula_id_idx on public.atividade (aula_id);

create table if not exists public.gabarito (
  atividade_id  bigint not null references public.atividade (id) on delete cascade,
  item          smallint not null check (item > 0),
  titulo        text,
  letra         char(1) not null check (letra in ('A', 'B', 'C', 'D')),
  primary key (atividade_id, item)
);

create table if not exists public.resposta_atividade (
  aluno_id       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  atividade_id   bigint not null references public.atividade (id) on delete cascade,
  item           smallint not null check (item > 0),
  letra          char(1) not null check (letra in ('A', 'B', 'C', 'D')),
  atualizado_em  timestamptz not null default now(),
  primary key (aluno_id, atividade_id, item)
);
create index if not exists resposta_atividade_atividade_idx on public.resposta_atividade (atividade_id);

create table if not exists public.entrega_atividade (
  aluno_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  atividade_id  bigint not null references public.atividade (id) on delete cascade,
  entregue_em   timestamptz not null default now(),
  primary key (aluno_id, atividade_id)
);

-- ── 3. Funções auxiliares das políticas ───────────────────────────────────────────────
create or replace function public.eh_professor()
returns boolean
language sql stable
set search_path = public
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'perfil') = 'PROFESSOR', false);
$$;

-- security definer: consulta as tabelas sem depender das políticas de quem chama
create or replace function public.atividade_entregue(p_atividade bigint)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.entrega_atividade e
    where e.aluno_id = auth.uid() and e.atividade_id = p_atividade
  );
$$;

create or replace function public.atividade_completa(p_atividade bigint)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select (select count(*) from public.resposta_atividade r
          where r.aluno_id = auth.uid() and r.atividade_id = p_atividade)
       = (select a.total_itens from public.atividade a where a.id = p_atividade);
$$;

create or replace function public.item_valido(p_atividade bigint, p_item smallint)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.atividade a
    where a.id = p_atividade and a.ativo and p_item <= a.total_itens
  );
$$;

revoke all on function public.atividade_entregue(bigint) from public;
revoke all on function public.atividade_completa(bigint) from public;
revoke all on function public.item_valido(bigint, smallint) from public;
grant execute on function public.eh_professor() to anon, authenticated;
grant execute on function public.atividade_entregue(bigint) to authenticated;
grant execute on function public.atividade_completa(bigint) to authenticated;
grant execute on function public.item_valido(bigint, smallint) to authenticated;

-- ── 4. RLS ────────────────────────────────────────────────────────────────────────────
alter table public.turma              enable row level security;
alter table public.aluno              enable row level security;
alter table public.atividade          enable row level security;
alter table public.gabarito           enable row level security;
alter table public.resposta_atividade enable row level security;
alter table public.entrega_atividade  enable row level security;

-- turma: qualquer usuário logado lê (nome/código da turma não é sensível)
drop policy if exists turma_select on public.turma;
create policy turma_select on public.turma
  for select to authenticated using (true);

-- aluno: cada aluno lê o próprio cadastro; professor lê todos. Escrita só pela service_role.
drop policy if exists aluno_select on public.aluno;
create policy aluno_select on public.aluno
  for select to authenticated using (id = auth.uid() or public.eh_professor());

-- atividade: leitura pública das ativas (página precisa achar o id sem login)
drop policy if exists atividade_select on public.atividade;
create policy atividade_select on public.atividade
  for select to anon, authenticated using (ativo or public.eh_professor());

-- gabarito: SOMENTE professor
drop policy if exists gabarito_select on public.gabarito;
create policy gabarito_select on public.gabarito
  for select to authenticated using (public.eh_professor());

-- resposta: aluno lê/grava as próprias, sem alterar depois de entregar; professor lê todas
drop policy if exists resposta_select on public.resposta_atividade;
create policy resposta_select on public.resposta_atividade
  for select to authenticated using (aluno_id = auth.uid() or public.eh_professor());

drop policy if exists resposta_insert on public.resposta_atividade;
create policy resposta_insert on public.resposta_atividade
  for insert to authenticated
  with check (
    aluno_id = auth.uid()
    and public.item_valido(atividade_id, item)
    and not public.atividade_entregue(atividade_id)
  );

drop policy if exists resposta_update on public.resposta_atividade;
create policy resposta_update on public.resposta_atividade
  for update to authenticated
  using (aluno_id = auth.uid() and not public.atividade_entregue(atividade_id))
  with check (
    aluno_id = auth.uid()
    and public.item_valido(atividade_id, item)
    and not public.atividade_entregue(atividade_id)
  );

-- entrega: aluno entrega uma vez, só com todos os itens respondidos; professor lê todas
drop policy if exists entrega_select on public.entrega_atividade;
create policy entrega_select on public.entrega_atividade
  for select to authenticated using (aluno_id = auth.uid() or public.eh_professor());

drop policy if exists entrega_insert on public.entrega_atividade;
create policy entrega_insert on public.entrega_atividade
  for insert to authenticated
  with check (aluno_id = auth.uid() and public.atividade_completa(atividade_id));

-- professor lê aulas e matérias (filtros do painel); só acrescenta acesso, não remove
drop policy if exists aulas_select_professor on public.aulas;
create policy aulas_select_professor on public.aulas
  for select to authenticated using (public.eh_professor());

drop policy if exists materia_select_professor on public.materia;
create policy materia_select_professor on public.materia
  for select to authenticated using (public.eh_professor());

-- ── 5. Permissões de tabela (as políticas acima decidem as linhas) ────────────────────
grant select on public.atividade to anon, authenticated;
grant select on public.turma, public.aluno, public.gabarito to authenticated;
grant select, insert, update on public.resposta_atividade to authenticated;
grant select, insert on public.entrega_atividade to authenticated;
grant select on public.aulas, public.materia, public.curso to authenticated;
